AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApiKeyValue:
    Type: String
    NoEcho: true
    Description: "API Key for the StufftodoTasksService"

Resources:
  StufftodoTasksService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "stufftodo-tasks-service"
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, POST, GET, PUT, DELETE'"
        AllowHeaders: "'Content-Type, x-api-key'"
        # AllowOrigin: "'http://localhost:5173'" # replace with frontend app URL
        AllowOrigin: "'https://stufftodo.phil-code.com'" # replace with frontend app URL
      Auth:
        ApiKeyRequired: true

  StufftodoApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: "StufftodoApiKey"
      Enabled: true
      Value: !Ref ApiKeyValue
      StageKeys:
        - RestApiId: !Ref StufftodoTasksService
          StageName: Prod

  StufftodoUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: "StufftodoUsagePlan"
      ApiStages:
        - ApiId: !Ref StufftodoTasksService
          Stage: Prod
      Throttle:
        RateLimit: 100
        BurstLimit: 20
      Quota:
        Limit: 10000
        Period: MONTH

  StufftodoUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref StufftodoApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref StufftodoUsagePlan


  StufftodoTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref StufftodoTasksTable
      Events:
        TasksOptions:
          Type: Api
          Properties:
            Path: /tasks
            Method: OPTIONS
            RestApiId: !Ref StufftodoTasksService
            Auth:
              ApiKeyRequired: false
        GetTask:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: GET
            RestApiId: !Ref StufftodoTasksService
        GetTasks:
          Type: Api
          Properties:
            Path: /tasks
            Method: GET
            RestApiId: !Ref StufftodoTasksService
        PutTask:
          Type: Api
          Properties:
            Path: /tasks
            Method: POST
            RestApiId: !Ref StufftodoTasksService
        DeleteTask:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: DELETE
            RestApiId: !Ref StufftodoTasksService
        UpdateTask:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: PUT
            RestApiId: !Ref StufftodoTasksService
    Metadata:
      BuildMethod: makefile

  StufftodoTasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StufftodoTasks
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
